/**
 * Generates supabase/seed.sql from the mock listings so the DB catalog and the
 * MockPropertyProvider stay identical. Run: npm run db:seed:generate
 */
import { writeFileSync } from "node:fs";
import { MOCK_PROPERTIES } from "../src/lib/providers/property/mock-data";

const q = (v: string | null) => (v === null ? "null" : `'${v.replace(/'/g, "''")}'`);
const rows = MOCK_PROPERTIES.map(
  (p) =>
    `  (${q(p.id)}, ${q(p.source)}, ${q(p.title)}, ${q(p.location)}, ${q(p.locality)}, ${q(p.city)}, ${p.rent}, ${p.utilitiesIncluded}, ${p.bedrooms}, ${p.bathrooms}, ${p.floor}, ${p.totalFloors}, ${p.lift}, ${q(p.parking)}, ${q(p.furnishing)}, ${p.petFriendly}, ${p.balcony}, array[${p.amenities.map(q).join(", ")}]::text[], ${p.latitude}, ${p.longitude}, ${q(p.listingUrl)}, ${q(p.imageUrl)}, ${q(p.description)})`,
);
const sql = `-- GENERATED by scripts/generate-seed.ts from src/lib/providers/property/mock-data.ts
-- Do not edit by hand. These are MOCK, illustrative Pune listings (not real offers).
insert into public.property_listings
  (id, source, title, location, locality, city, rent, utilities_included, bedrooms, bathrooms, floor, total_floors, lift, parking, furnishing, pet_friendly, balcony, amenities, latitude, longitude, listing_url, image_url, description)
values
${rows.join(",\n")}
on conflict (id) do update set
  source = excluded.source, title = excluded.title, location = excluded.location, locality = excluded.locality,
  city = excluded.city, rent = excluded.rent, utilities_included = excluded.utilities_included,
  bedrooms = excluded.bedrooms, bathrooms = excluded.bathrooms, floor = excluded.floor,
  total_floors = excluded.total_floors, lift = excluded.lift, parking = excluded.parking,
  furnishing = excluded.furnishing, pet_friendly = excluded.pet_friendly, balcony = excluded.balcony,
  amenities = excluded.amenities, latitude = excluded.latitude, longitude = excluded.longitude,
  listing_url = excluded.listing_url, image_url = excluded.image_url, description = excluded.description;
`;
writeFileSync("supabase/seed.sql", sql);
console.log(`Wrote ${MOCK_PROPERTIES.length} listings to supabase/seed.sql`);
