import type { Property } from "@/lib/matching/types";

/**
 * MOCK Pune listings.
 *
 * These are fictional, illustrative listings created for the FlatMatch MVP.
 * Society names are invented. Rents are realistic for 2025–26 Pune but are
 * not real offers. Coordinates are approximate locality centroids.
 *
 * supabase/seed.sql is generated from this file (npm run db:seed:generate)
 * so the database catalog and the in-app mock provider never drift apart.
 */
const img = (n: number) => `/listings/flat-${n}.svg`;

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "pune-wakad-palm-grove",
    title: "3BHK at Palm Grove Residency",
    location: "Datta Mandir Road, Wakad",
    locality: "Wakad",
    city: "Pune",
    rent: 45000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 6,
    totalFloors: 12,
    lift: true,
    parking: "car",
    furnishing: "semi-furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security", "gym"],
    latitude: 18.5987,
    longitude: 73.7688,
    listingUrl: null,
    imageUrl: img(1),
    description:
      "Semi-furnished 3BHK in a gated society with gym and 24x7 water. Wardrobes and kitchen fitted; beds not included. Owner is fine with a small pet.",
    source: "mock",
  },
  {
    id: "pune-baner-silver-oak",
    title: "3BHK at Silver Oak Heights",
    location: "Pan Card Club Road, Baner",
    locality: "Baner",
    city: "Pune",
    rent: 48000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 3,
    totalFloors: 7,
    lift: true,
    parking: "car",
    furnishing: "furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security"],
    latitude: 18.559,
    longitude: 73.7868,
    listingUrl: null,
    imageUrl: img(2),
    description:
      "Fully furnished 3BHK with two balconies close to Baner Road cafes. Covered car parking. Pets allowed with a deposit.",
    source: "mock",
  },
  {
    id: "pune-balewadi-skyline",
    title: "3BHK at Skyline Towers",
    location: "Near Balewadi High Street",
    locality: "Balewadi",
    city: "Pune",
    rent: 51000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 3,
    floor: 9,
    totalFloors: 14,
    lift: true,
    parking: "car",
    furnishing: "semi-furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security", "gym"],
    latitude: 18.5767,
    longitude: 73.7792,
    listingUrl: null,
    imageUrl: img(3),
    description:
      "Semi-furnished 3BHK with three bathrooms and a large balcony on the 9th floor. Society gym and clubhouse. Walking distance to Balewadi High Street.",
    source: "mock",
  },
  {
    id: "pune-aundh-green-court",
    title: "3BHK at Green Court",
    location: "ITI Road, Aundh",
    locality: "Aundh",
    city: "Pune",
    rent: 45000,
    utilitiesIncluded: true,
    bedrooms: 3,
    bathrooms: 2,
    floor: 2,
    totalFloors: 4,
    lift: false,
    parking: "two-wheeler",
    furnishing: "furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["power_backup", "water_24x7", "security"],
    latitude: 18.558,
    longitude: 73.8075,
    listingUrl: null,
    imageUrl: img(4),
    description:
      "Furnished 3BHK on the 2nd floor of a low-rise building (no lift). Maintenance and water included in rent. Two-wheeler parking only.",
    source: "mock",
  },
  {
    id: "pune-kothrud-karishma",
    title: "3BHK at Karishma Enclave",
    location: "Karve Road, Kothrud",
    locality: "Kothrud",
    city: "Pune",
    rent: 39000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 4,
    totalFloors: 10,
    lift: true,
    parking: "car",
    furnishing: "furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security", "near_metro"],
    latitude: 18.5074,
    longitude: 73.8077,
    listingUrl: null,
    imageUrl: img(5),
    description:
      "Well-priced furnished 3BHK near Karve Road metro. Quiet residential lane, car parking, pets welcome.",
    source: "mock",
  },
  {
    id: "pune-baner-mahalunge-walkup",
    title: "3BHK top-floor walk-up",
    location: "Mahalunge Road, Baner",
    locality: "Baner",
    city: "Pune",
    rent: 40500,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 5,
    totalFloors: 5,
    lift: false,
    parking: "car",
    furnishing: "semi-furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["power_backup", "water_24x7"],
    latitude: 18.5625,
    longitude: 73.7801,
    listingUrl: null,
    imageUrl: img(6),
    description:
      "Spacious 5th-floor 3BHK with terrace access. The building has no lift. Good price for Baner.",
    source: "mock",
  },
  {
    id: "pune-hinjewadi-infinity",
    title: "3BHK at Infinity Park",
    location: "Phase 1, Hinjewadi",
    locality: "Hinjewadi",
    city: "Pune",
    rent: 43500,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 3,
    floor: 7,
    totalFloors: 15,
    lift: true,
    parking: "car",
    furnishing: "furnished",
    petFriendly: false,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security", "gym"],
    latitude: 18.5925,
    longitude: 73.742,
    listingUrl: null,
    imageUrl: img(7),
    description:
      "Furnished 3BHK walking distance from Phase 1 offices. Society rules do not allow pets.",
    source: "mock",
  },
  {
    id: "pune-hinjewadi-blue-ridge",
    title: "3BHK at Blue Ridge Township",
    location: "Phase 1, Hinjewadi",
    locality: "Hinjewadi",
    city: "Pune",
    rent: 42000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 11,
    totalFloors: 18,
    lift: true,
    parking: "car",
    furnishing: "semi-furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security", "gym"],
    latitude: 18.5876,
    longitude: 73.7361,
    listingUrl: null,
    imageUrl: img(8),
    description:
      "Township flat with jogging track and pet park. 5 minutes from Phase 1, but a long drive to central Pune.",
    source: "mock",
  },
  {
    id: "pune-baner-2bhk-sus-road",
    title: "2BHK at Sus Road",
    location: "Sus Road, Baner",
    locality: "Baner",
    city: "Pune",
    rent: 32000,
    utilitiesIncluded: false,
    bedrooms: 2,
    bathrooms: 2,
    floor: 3,
    totalFloors: 8,
    lift: true,
    parking: "car",
    furnishing: "furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security"],
    latitude: 18.5555,
    longitude: 73.7792,
    listingUrl: null,
    imageUrl: img(2),
    description: "Furnished 2BHK. Attractive rent, but only two bedrooms.",
    source: "mock",
  },
  {
    id: "pune-vimannagar-lake-view",
    title: "3BHK at Lake View Apartments",
    location: "Viman Nagar",
    locality: "Viman Nagar",
    city: "Pune",
    rent: 50000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 5,
    totalFloors: 9,
    lift: true,
    parking: "car",
    furnishing: "furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security"],
    latitude: 18.5679,
    longitude: 73.9143,
    listingUrl: null,
    imageUrl: img(3),
    description: "Furnished 3BHK near Phoenix Marketcity, on the east side of the city.",
    source: "mock",
  },
  {
    id: "pune-pimplesaudagar-rose",
    title: "3BHK at Rose Valley",
    location: "Kunal Icon Road, Pimple Saudagar",
    locality: "Pimple Saudagar",
    city: "Pune",
    rent: 36000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 1,
    floor: 4,
    totalFloors: 8,
    lift: true,
    parking: "car",
    furnishing: "semi-furnished",
    petFriendly: true,
    balcony: false,
    amenities: ["power_backup", "security"],
    latitude: 18.5987,
    longitude: 73.7976,
    listingUrl: null,
    imageUrl: img(4),
    description: "Budget 3BHK with a single shared bathroom. No balcony.",
    source: "mock",
  },
  {
    id: "pune-pashan-hillside",
    title: "3BHK at Hillside Residency",
    location: "Pashan–Sus Road, Pashan",
    locality: "Pashan",
    city: "Pune",
    rent: 54000,
    utilitiesIncluded: true,
    bedrooms: 3,
    bathrooms: 3,
    floor: 3,
    totalFloors: 6,
    lift: true,
    parking: "car",
    furnishing: "furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security"],
    latitude: 18.5389,
    longitude: 73.7925,
    listingUrl: null,
    imageUrl: img(5),
    description: "Premium furnished 3BHK facing the hills, utilities included. Higher rent.",
    source: "mock",
  },
  {
    id: "pune-sus-meadows",
    title: "3BHK at Sus Meadows",
    location: "Sus Gaon",
    locality: "Sus",
    city: "Pune",
    rent: 36000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 6,
    totalFloors: 10,
    lift: true,
    parking: "car",
    furnishing: "unfurnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "water_24x7", "security"],
    latitude: 18.5416,
    longitude: 73.7458,
    listingUrl: null,
    imageUrl: img(6),
    description: "New unfurnished 3BHK at a low rent. No power backup yet.",
    source: "mock",
  },
  {
    id: "pune-balewadi-grand",
    title: "3BHK at The Grand Balewadi",
    location: "Balewadi Phata",
    locality: "Balewadi",
    city: "Pune",
    rent: 60000,
    utilitiesIncluded: true,
    bedrooms: 3,
    bathrooms: 3,
    floor: 12,
    totalFloors: 20,
    lift: true,
    parking: "car",
    furnishing: "furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security", "gym", "air_conditioning"],
    latitude: 18.5733,
    longitude: 73.7722,
    listingUrl: null,
    imageUrl: img(7),
    description: "Luxury furnished 3BHK with AC in every room. Everything included, at a premium.",
    source: "mock",
  },
  {
    id: "pune-wakad-bhumkar-walkup",
    title: "3BHK independent floor",
    location: "Bhumkar Chowk, Wakad",
    locality: "Wakad",
    city: "Pune",
    rent: 33000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 2,
    totalFloors: 3,
    lift: false,
    parking: "two-wheeler",
    furnishing: "unfurnished",
    petFriendly: false,
    balcony: false,
    amenities: ["water_24x7"],
    latitude: 18.6011,
    longitude: 73.7571,
    listingUrl: null,
    imageUrl: img(8),
    description: "Cheap independent floor. Landlord lives downstairs and does not allow pets.",
    source: "mock",
  },
  {
    id: "pune-bavdhan-riverside",
    title: "3BHK at Riverside Greens",
    location: "Chandani Chowk, Bavdhan",
    locality: "Bavdhan",
    city: "Pune",
    rent: 46500,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 8,
    totalFloors: 11,
    lift: true,
    parking: "car",
    furnishing: "furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "security"],
    latitude: 18.5176,
    longitude: 73.7784,
    listingUrl: null,
    imageUrl: img(1),
    description: "Furnished 3BHK with hill views. Water supply is tanker-dependent in summer.",
    source: "mock",
  },
  {
    id: "pune-aundh-westend",
    title: "3BHK at Westend Residences",
    location: "Westend Mall Road, Aundh",
    locality: "Aundh",
    city: "Pune",
    rent: 57000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 8,
    totalFloors: 12,
    lift: true,
    parking: "car",
    furnishing: "semi-furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security", "gym"],
    latitude: 18.5617,
    longitude: 73.8076,
    listingUrl: null,
    imageUrl: img(2),
    description: "Semi-furnished 3BHK near Westend Mall. Premium location, premium rent.",
    source: "mock",
  },
  {
    id: "pune-pimplenilakh-orchid",
    title: "3BHK at Orchid Park",
    location: "Pimple Nilakh",
    locality: "Pimple Nilakh",
    city: "Pune",
    rent: 42000,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    floor: 5,
    totalFloors: 9,
    lift: true,
    parking: "car",
    furnishing: "semi-furnished",
    petFriendly: true,
    balcony: true,
    amenities: ["gated_society", "power_backup", "water_24x7", "security"],
    latitude: 18.575,
    longitude: 73.787,
    listingUrl: null,
    imageUrl: img(3),
    description: "Semi-furnished 3BHK across the river from Baner, quieter and slightly cheaper.",
    source: "mock",
  },
];
